### PR TITLE
Renamed, moved to server

### PR DESCRIPTION
**Pull request by sphaso**

### CODE REVIEW

**Comment by paddatrapper** [comment]
Nice work! There are a couple of references to the datastructures package from the client EditorTest.java unit test though that prevent compiling of the client

**Comment by paddatrapper** [comment]
Nice work! There are a couple of references to the datastructures package from the client EditorTest.java unit test though that prevent compiling of the client

**Comment by sphaso** [comment]
That's weird, it built fine on my machine. New commit-push should have fixed that reference issue

**Comment by paddatrapper** [comment]
It also built fine on mine, but failed the Travis CI build

**Pull request merged**
